### ISSUE TITLE
Specify how many decimal places to keep?

### ISSUE THREAD

**Issue by joncursi** [nfriedly/approximate-number#16]
```js
approx(64876440039.52) // comes out as: 64b
```

I want this to read "64.8b" or "64.9b" based on rounding. Would be great if you could specify in the config option how many decimal places you want to keep.

**Comment by nfriedly** [comment]
That's a good idea. Maybe call it `decimalPlaces` -  leave as undefined or set to null for current behavior, or set to a number, e.g. `1` for your desired output.

Do you think you could send a pull request and some tests for that?
