### ISSUE TITLE
'captital: true' not functioning

### ISSUE THREAD

**Issue by nobodyshome** [nfriedly/approximate-number#18]
It's mentioned in the docs with one of the examples that setting 'capital: true' should work but it does not seem to be for me.

docs code:
`console.log('The US national debt is %s.', approx(19939034457936, {prefix: '$', capital: true, round: true}));`
my code:
`console.log(approx(input, {min10k: true, captital: true, suffix: '+'})`

**Comment by nobodyshome** [comment]
It appears to be implemented [here](https://github.com/nfriedly/approximate-number/blob/97d0a7e475e1bbd1bf4e95ddc5efdccf41a05234/lib/approximate-number.js#L97)
However, it's missing from the params [here](https://github.com/nfriedly/approximate-number/blob/master/lib/approximate-number.js#L59)

**Comment by nfriedly** [comment]
It looks like there's an extra `t` in your `captital` - it should be `capital`.

I'll go ahead and correct the documentation though.
